const countryList = {
    USD: "US",
    INR: "IN",
    EUR: "FR",
    GBP: "GB",
    AUD: "AU",
    CAD: "CA",
    JPY: "JP",
    CNY: "CN",
    NZD: "NZ",
    CHF: "CH",
    SGD: "SG",
    HKD: "HK",
    SEK: "SE",
    KRW: "KR",
    NOK: "NO",
    MXN: "MX",
    BRL: "BR",
    RUB: "RU",
    ZAR: "ZA",
    TRY: "TR",
    IDR: "ID",
    MYR: "MY",
    PHP: "PH",
    THB: "TH",
    VND: "VN",
  };
  